const menus = [
  {
    childs: [
      {
        id: 1194020,
        funName: 'MyMerits',
        funTitle: '我的绩效',
        funUrl: '/admin/biz1/page1',
        funLogo: '',
      },
      {
        childs: [
          {
            id: 1194016,
            funName: 'Dyejikaohe',
            funTitle: '业绩考核',
            funUrl: '/admin/biz1/page2',
          },
          {
            id: 1194017,
            funName: 'Dwenhuakaohe',
            funTitle: '文化考核',
            funUrl: '/admin/biz1/page1',
            funLogo: '',
          },
          {
            id: 1195009,
            funName: 'Dqitakaohe',
            funTitle: '其他考核',
            funUrl: '/admin/biz1/page2',
            funLogo: '',
          },
        ],
        id: 1195008,
        funName: 'bumenjixiao',
        funTitle: '部门绩效管理',
        funUrl: '/admin/biz1/page2',
        funLogo: '',
      },
      {
        childs: [
          {
            id: 1078003,
            funName: 'InventoryManagement',
            funTitle: '盘点管理',
            funUrl: '/admin/biz2/page1',
            funLogo: '',
          },
          {
            id: 1078002,
            funName: 'TeamInventory',
            funTitle: '团队盘点',
            funUrl: '/admin/biz2/page2',
            funLogo: '',
          },
        ],
        id: 1078001,
        funName: 'Talentinventory',
        funTitle: '人才盘点',
        funUrl: '',
        funLogo: '',
      },
      {
        childs: [
          {
            id: 1087001,
            funName: 'NominationManager',
            funTitle: '提名确认',
            funUrl: '/admin/biz2/page1',
            funLogo: '',
          },
          {
            id: 1086002,
            funName: 'PromotionManager',
            funTitle: '晋升提名',
            funUrl: '/admin/biz2/page2',
            funLogo: '',
          },
        ],
        id: 1086001,
        funName: 'PromotionNomination',
        funTitle: '晋升提名',
        funUrl: '',
        funLogo: '',
      },
    ],
    id: 1065001,
    funName: 'hrManage',
    funTitle: '人事管理',
    funUrl: '',
    funLogo: 'magi-hr',
  },
  {
    childs: [
      {
        childs: [
          {
            id: 1114001,
            funName: 'myOAnew',
            funTitle: '我的OA',
            funUrl: '/admin/biz1/page1',
            funLogo: '',
          },
        ],
        id: 1111002,
        funName: 'OAoffice',
        funTitle: 'OA办公',
        funUrl: '',
        funLogo: '',
      },
      {
        id: 1182002,
        funName: 'documentcenter',
        funTitle: '文档中心',
        funUrl: '/admin/biz2/page2',
        funLogo: '',
      },
      {
        childs: [
          {
            id: 1182001,
            funName: 'myWorkSystem',
            funTitle: '我的工单',
            funUrl: '/admin/biz1/page1',
            funLogo: '',
          },
        ],
        id: 1181001,
        funName: 'workSystem',
        funTitle: '工单管理',
        funUrl: '',
        funLogo: '',
      },
      {
        id: 1091001,
        funName: 'kehuguanli',
        funTitle: 'CRM客户管理',
        funUrl: '/admin/biz2/page1',
        funLogo: '',
      },
      {
        id: 1189001,
        funName: 'calendar',
        funTitle: '日程管理',
        funUrl: '/admin/biz2/page1',
        funLogo: '',
        funMiniLogo: '',
      },
    ],
    id: 1066002,
    funName: 'nOA',
    funTitle: '协同办公',
    funUrl: '',
    funLogo: 'magi-oa',
  },
  {
    childs: [
      {
        id: 1178001,
        funName: 'videoConference',
        funTitle: '视频会议',
        funUrl: '/admin/biz2/page2',
        funLogo: '',
      },
    ],
    id: 1177002,
    funName: 'videomeetings',
    funTitle: '视频会议',
    funUrl: '',
    funLogo: '',
  },
  {
    childs: [
      {
        id: 1104001,
        funName: 'MyProject',
        funTitle: '我的项目',
        funUrl: '/admin/biz2/page1',
        funLogo: '',
      },
      {
        id: 1103002,
        funName: 'ProjectAlication',
        funTitle: '我的申请',
        funUrl: '/admin/biz2/page2',
        funLogo: '',
      },
      {
        id: 1103003,
        funName: 'ProjectApproval',
        funTitle: '我的审批',
        funUrl: '/admin/biz1/page1',
        funLogo: '',
      },
    ],
    id: 1103001,
    funName: 'ProjectManagement',
    funTitle: '项目管理',
    funUrl: '',
    funLogo: '',
  },
  {
    childs: [
      {
        id: 1036010,
        funName: 'examineApprove',
        funTitle: '合同审批',
        funUrl: '/admin/biz1/page1',
        funLogo: '',
      },
      {
        id: 1037015,
        funName: 'partner',
        funTitle: '签约方管理',
        funUrl: '/admin/biz1/page2',
        funLogo: '',
      },
      {
        id: 1053010,
        funName: 'relatedParty',
        funTitle: '关联方管理',
        funUrl: '/admin/biz2/page1',
        funLogo: '',
      },
    ],
    id: 1037014,
    funName: 'contractmanagement',
    funTitle: '合同管理-科技',
    funUrl: '',
    funLogo: '',
  },
];

export default menus;
