//  https://api.zuifuli.com/api/duncan/v1/cfg/load?type=RelationTypeEnum
export const relation = [
  { text: '父母', code: 'P', value: 'P' },
  { text: '子女', code: 'C', value: 'C' },
  { text: '配偶', code: 'S', value: 'S' },
  { text: '同事', code: 'W', value: 'W' },
  { text: '自己', code: 'S', value: 'S' },
  { text: '其他', code: 'O', value: 'O' },
];

//  https://api.zuifuli.com/api/duncan/v1/cfg/load?type=CertiTypeEnum
export const certType = [
  { text: '身份证', code: 'I', value: 'I', label: '身份证' },
  { text: '护照', code: 'P', value: 'P', label: '护照' },
  { text: '出生证', code: 'B', value: 'B', label: '出生证' },
  { text: '驾照', code: 'D', value: 'D', label: '驾照' },
  { text: '军官证', code: 'M', value: 'M', label: '军官证' },
  { text: '其他', code: 'Q', value: 'Q', label: '其他' },
  { text: '税务登记证', code: 'T', value: 'T', label: '税务登记证' },
  { text: '执照', code: 'L', value: 'L', label: '执照' },
  { text: '组织机构证', code: 'O', value: 'O', label: '组织机构证' },
  { text: '港台同胞证', code: 'GT', value: 'GT', label: '港台同胞证' },
  { text: '士兵证', code: 'S', value: 'S', label: '士兵证' },
  { text: '返乡证', code: 'F', value: 'F', label: '返乡证' },
  { text: '组织机构代码', code: 'Z', value: 'Z', label: '组织机构代码' },
  { text: '港澳通行证', code: 'GA', value: 'GA', label: '港澳通行证' },
  { text: '台湾通行证', code: 'TW', value: 'TW', label: '台湾通行证' },
  { text: '户口簿', code: 'H', value: 'H', label: '户口簿' },
  { text: '学生证', code: 'X', value: 'X', label: '学生证' },
  { text: '国际海员证', code: 'G', value: 'G', label: '国际海员证' },
  { text: '外国人永久居留证', code: 'J', value: 'J', label: '外国人永久居留证' },
  { text: '旅行证', code: 'LX', value: 'LX', label: '旅行证' },
  { text: '警官证', code: 'PL', value: 'PL', label: '警官证' },
  { text: '港澳居民来往内地通行证', code: 'GJ', value: 'GJ', label: '港澳居民来往内地通行证' },
  { text: '台胞证', code: 'TB', value: 'TB', label: '台胞证' },
  { text: '统一社会信用代码', code: 'TY', value: 'TY', label: '统一社会信用代码' },
];

export const hasSocialInsurance = [
  { code: 'Y', text: '有 (含新农合)' },
  { code: 'N', text: '无' },
];

export const maritalStatus = [
  { text: '已婚', code: 'Y' },
  { text: '未婚', code: 'N' },
];

// https://api.zuifuli.com/api/duncan/v1/cfg/load?type=PoliticStatusEnum
//政治面貌
export const politicStatus = [
  { label: '中共党员', value: 'CP' },
  { label: '中共预备党员', value: 'PRE' },
  { label: '民主党派', value: 'DP' },
  { label: '共青团员', value: 'LM' },
  { label: '群众', value: 'PP' },
];

// https://api.zuifuli.com/api/duncan/v1/cfg/load?type=EducationLevelEnum
export const educationLevel = [
  { label: '小学', value: 'PS' },
  { label: '初中', value: 'JS' },
  { label: '中专', value: 'STS' },
  { label: '高中', value: 'SMS' },
  { label: '大专', value: 'C' },
  { label: '本科', value: 'U' },
  { label: '硕士', value: 'M' },
  { label: '博士', value: 'D' },
  { label: '博士后', value: 'P' },
  { label: '其他', value: 'O' },
];

// https://api.zuifuli.com/api/duncan/v1/cfg/load?type=HouseholdTypeEnum
export const householdType = [
  { label: '城镇', value: 'U' },
  { label: '农业', value: 'R' },
  { label: '外地城镇（省内）', value: 'IU' },
  { label: '外地农村（省内）', value: 'IR' },
  { label: '外地城镇（省外）', value: 'OU' },
  { label: '外地农村（省外）', value: 'OR' },
];

// https://t-api.zuifuli.com/api/duncan/v1/cfg/load?type=MinZu 民族
export const nationalities = [
  { label: '汉族', code: '01', value: '01' },
  { label: '蒙古族', code: '02', value: '02' },
  { label: '回族', code: '03', value: '03' },
  { label: '藏族', code: '04', value: '04' },
  { label: '维吾尔族', code: '05', value: '05' },
  { label: '苗族', code: '06', value: '06' },
  { label: '彝族', code: '07', value: '07' },
  { label: '壮族', code: '08', value: '08' },
  { label: '布依族', code: '09', value: '09' },
  { label: '朝鲜族', code: '10', value: '10' },
  { label: '满族', code: '11', value: '11' },
  { label: '侗族', code: '12', value: '12' },
  { label: '瑶族', code: '13', value: '13' },
  { label: '白族', code: '14', value: '14' },
  { label: '土家族', code: '15', value: '15' },
  { label: '哈尼族', code: '16', value: '16' },
  { label: '哈萨克族', code: '17', value: '17' },
  { label: '傣族', code: '18', value: '18' },
  { label: '黎族', code: '19', value: '19' },
  { label: '傈僳族', code: '20', value: '20' },
  { label: '佤族', code: '21', value: '21' },
  { label: '畲族', code: '22', value: '22' },
  { label: '高山族', code: '23', value: '23' },
  { label: '拉祜族', code: '24', value: '24' },
  { label: '水族', code: '25', value: '25' },
  { label: '东乡族', code: '26', value: '26' },
  { label: '纳西族', code: '27', value: '27' },
  { label: '景颇族', code: '28', value: '28' },
  { label: '柯尔克孜族', code: '29', value: '29' },
  { label: '土族', code: '30', value: '30' },
  { label: '达斡尔族', code: '31', value: '31' },
  { label: '仫佬族', code: '32', value: '32' },
  { label: '羌族', code: '33', value: '33' },
  { label: '布朗族', code: '34', value: '34' },
  { label: '撒拉族', code: '35', value: '35' },
  { label: '毛南族', code: '36', value: '36' },
  { label: '仡佬族', code: '37', value: '37' },
  { label: '锡伯族', code: '38', value: '38' },
  { label: '阿昌族', code: '39', value: '39' },
  { label: '普米族', code: '40', value: '40' },
  { label: '塔吉克族', code: '41', value: '41' },
  { label: '怒族', code: '42', value: '42' },
  { label: '乌孜别克族', code: '43', value: '43' },
  { label: '俄罗斯族', code: '44', value: '44' },
  { label: '鄂温克族', code: '45', value: '45' },
  { label: '德昂族', code: '46', value: '46' },
  { label: '保安族', code: '47', value: '47' },
  { label: '裕固族', code: '48', value: '48' },
  { label: '京族', code: '49', value: '49' },
  { label: '塔塔尔族', code: '50', value: '50' },
  { label: '独龙族', code: '51', value: '51' },
  { label: '鄂伦春族', code: '52', value: '52' },
  { label: '赫哲族', code: '53', value: '53' },
  { label: '门巴族', code: '54', value: '54' },
  { label: '珞巴族', code: '54', value: '54' },
  { label: '基诺族', code: '56', value: '56' },
  { label: '其他', code: '57', value: '57' },
];

// 国家 https://t-api.zuifuli.com/api/duncan/v1/cfg/load?type=NationalityEnum
export const coutries = [
  { label: '中华人民共和国', code: 'CN', value: 'CN' },
  { label: '中国香港', code: 'HK', value: 'HK' },
  { label: '中国澳门', code: 'MO', value: 'MO' },
  { label: '中国台湾', code: 'TW', value: 'TW' },
  { label: '安道尔', code: 'AD', value: 'AD' },
  { label: '阿联酋', code: 'AE', value: 'AE' },
  { label: '阿富汗', code: 'AF', value: 'AF' },
  { label: '安提瓜和巴布达', code: 'AG', value: 'AG' },
  { label: '安圭拉', code: 'AI', value: 'AI' },
  { label: '阿尔巴尼亚', code: 'AL', value: 'AL' },
  { label: '亚美尼亚', code: 'AM', value: 'AM' },
  { label: '荷属安的列斯', code: 'AN', value: 'AN' },
  { label: '安哥拉', code: 'AO', value: 'AO' },
  { label: '南极洲', code: 'AQ', value: 'AQ' },
  { label: '阿根廷', code: 'AR', value: 'AR' },
  { label: '美属萨摩亚', code: 'AS', value: 'AS' },
  { label: '奥地利', code: 'AT', value: 'AT' },
  { label: '澳大利亚', code: 'AU', value: 'AU' },
  { label: '阿鲁巴', code: 'AW', value: 'AW' },
  { label: '阿塞拜疆', code: 'AZ', value: 'AZ' },
  { label: '波黑', code: 'BA', value: 'BA' },
  { label: '巴巴多斯', code: 'BB', value: 'BB' },
  { label: '孟加拉国', code: 'BD', value: 'BD' },
  { label: '比利时', code: 'BE', value: 'BE' },
  { label: '布基纳法索', code: 'BF', value: 'BF' },
  { label: '保加利亚', code: 'BG', value: 'BG' },
  { label: '巴林', code: 'BH', value: 'BH' },
  { label: '布隆迪', code: 'BI', value: 'BI' },
  { label: '贝宁', code: 'BJ', value: 'BJ' },
  { label: '百慕大', code: 'BM', value: 'BM' },
  { label: '文莱', code: 'BN', value: 'BN' },
  { label: '玻利维亚', code: 'BO', value: 'BO' },
  { label: '巴西', code: 'BR', value: 'BR' },
  { label: '巴哈马', code: 'BS', value: 'BS' },
  { label: '不丹', code: 'BT', value: 'BT' },
  { label: '布维岛', code: 'BV', value: 'BV' },
  { label: '博茨瓦纳', code: 'BW', value: 'BW' },
  { label: '白俄罗斯', code: 'BY', value: 'BY' },
  { label: '伯利兹', code: 'BZ', value: 'BZ' },
  { label: '加拿大', code: 'CA', value: 'CA' },
  { label: '科科斯（基林）群岛', code: 'CC', value: 'CC' },
  { label: '刚果（金）', code: 'CD', value: 'CD' },
  { label: '中非', code: 'CF', value: 'CF' },
  { label: '刚果（布）', code: 'CG', value: 'CG' },
  { label: '瑞士', code: 'CH', value: 'CH' },
  { label: '科特迪瓦', code: 'CI', value: 'CI' },
  { label: '库克群岛', code: 'CK', value: 'CK' },
  { label: '智利', code: 'CL', value: 'CL' },
  { label: '喀麦隆', code: 'CM', value: 'CM' },
  { label: '哥伦比亚', code: 'CO', value: 'CO' },
  { label: '哥斯达黎加', code: 'CR', value: 'CR' },
  { label: '塞尔维亚', code: 'CS', value: 'CS' },
  { label: '古巴', code: 'CU', value: 'CU' },
  { label: '佛得角', code: 'CV', value: 'CV' },
  { label: '圣诞岛', code: 'CX', value: 'CX' },
  { label: '塞浦路斯', code: 'CY', value: 'CY' },
  { label: '捷克', code: 'CZ', value: 'CZ' },
  { label: '德国', code: 'DE', value: 'DE' },
  { label: '吉布提', code: 'DJ', value: 'DJ' },
  { label: '丹麦', code: 'DK', value: 'DK' },
  { label: '多米尼克', code: 'DM', value: 'DM' },
  { label: '多米尼加', code: 'DO', value: 'DO' },
  { label: '阿尔及利亚', code: 'DZ', value: 'DZ' },
  { label: '厄瓜多尔', code: 'EC', value: 'EC' },
  { label: '爱沙尼亚', code: 'EE', value: 'EE' },
  { label: '埃及', code: 'EG', value: 'EG' },
  { label: '西撒哈拉', code: 'EH', value: 'EH' },
  { label: '厄立特里亚', code: 'ER', value: 'ER' },
  { label: '西班牙', code: 'ES', value: 'ES' },
  { label: '埃塞俄比亚', code: 'ET', value: 'ET' },
  { label: '芬兰', code: 'FI', value: 'FI' },
  { label: '斐济', code: 'FJ', value: 'FJ' },
  { label: '福克兰群岛（马尔维纳斯）', code: 'FK', value: 'FK' },
  { label: '密克罗尼西亚', code: 'FM', value: 'FM' },
  { label: '法罗群岛', code: 'FO', value: 'FO' },
  { label: '法国', code: 'FR', value: 'FR' },
  { label: '加蓬', code: 'GA', value: 'GA' },
  { label: '英国', code: 'GB', value: 'GB' },
  { label: '格林纳达', code: 'GD', value: 'GD' },
  { label: '格鲁吉亚', code: 'GE', value: 'GE' },
  { label: '法属圭亚那', code: 'GF', value: 'GF' },
  { label: '加纳', code: 'GH', value: 'GH' },
  { label: '直布罗陀', code: 'GI', value: 'GI' },
  { label: '格陵兰', code: 'GL', value: 'GL' },
  { label: '冈比亚', code: 'GM', value: 'GM' },
  { label: '几内亚', code: 'GN', value: 'GN' },
  { label: '瓜德罗普', code: 'GP', value: 'GP' },
  { label: '赤道几内亚', code: 'GQ', value: 'GQ' },
  { label: '希腊', code: 'GR', value: 'GR' },
  { label: '南乔治亚岛和南桑德韦奇岛', code: 'GS', value: 'GS' },
  { label: '危地马拉', code: 'GT', value: 'GT' },
  { label: '关岛', code: 'GU', value: 'GU' },
  { label: '几内亚比绍', code: 'GW', value: 'GW' },
  { label: '圭亚那', code: 'GY', value: 'GY' },
  { label: '赫德岛和麦克唐纳岛', code: 'HM', value: 'HM' },
  { label: '洪都拉斯', code: 'HN', value: 'HN' },
  { label: '克罗地亚', code: 'HR', value: 'HR' },
  { label: '海地', code: 'HT', value: 'HT' },
  { label: '匈牙利', code: 'HU', value: 'HU' },
  { label: '印度尼西亚', code: 'ID', value: 'ID' },
  { label: '爱尔兰', code: 'IE', value: 'IE' },
  { label: '以色列', code: 'IL', value: 'IL' },
  { label: '印度', code: 'IN', value: 'IN' },
  { label: '英属印度洋领地', code: 'IO', value: 'IO' },
  { label: '伊拉克', code: 'IQ', value: 'IQ' },
  { label: '伊朗', code: 'IR', value: 'IR' },
  { label: '冰岛', code: 'IS', value: 'IS' },
  { label: '意大利', code: 'IT', value: 'IT' },
  { label: '牙买加', code: 'JM', value: 'JM' },
  { label: '约旦', code: 'JO', value: 'JO' },
  { label: '日本', code: 'JP', value: 'JP' },
  { label: '肯尼亚', code: 'KE', value: 'KE' },
  { label: '吉尔吉斯斯坦', code: 'KG', value: 'KG' },
  { label: '柬埔寨', code: 'KH', value: 'KH' },
  { label: '基里巴斯', code: 'KI', value: 'KI' },
  { label: '科摩罗', code: 'KM', value: 'KM' },
  { label: '圣基茨和尼维斯', code: 'KN', value: 'KN' },
  { label: '朝鲜', code: 'KP', value: 'KP' },
  { label: '韩国', code: 'KR', value: 'KR' },
  { label: '科威特', code: 'KW', value: 'KW' },
  { label: '开曼群岛', code: 'KY', value: 'KY' },
  { label: '哈萨克斯坦', code: 'KZ', value: 'KZ' },
  { label: '老挝', code: 'LA', value: 'LA' },
  { label: '黎巴嫩', code: 'LB', value: 'LB' },
  { label: '圣卢西亚', code: 'LC', value: 'LC' },
  { label: '列支敦士登', code: 'LI', value: 'LI' },
  { label: '斯里兰卡', code: 'LK', value: 'LK' },
  { label: '利比里亚', code: 'LR', value: 'LR' },
  { label: '莱索托', code: 'LS', value: 'LS' },
  { label: '立陶宛', code: 'LT', value: 'LT' },
  { label: '卢森堡', code: 'LU', value: 'LU' },
  { label: '拉脱维亚', code: 'LV', value: 'LV' },
  { label: '利比亚', code: 'LY', value: 'LY' },
  { label: '摩洛哥', code: 'MA', value: 'MA' },
  { label: '摩纳哥', code: 'MC', value: 'MC' },
  { label: '摩尔多瓦', code: 'MD', value: 'MD' },
  { label: '马达加斯加', code: 'MG', value: 'MG' },
  { label: '马绍尔群岛', code: 'MH', value: 'MH' },
  { label: '前南马其顿', code: 'MK', value: 'MK' },
  { label: '马里', code: 'ML', value: 'ML' },
  { label: '缅甸', code: 'MM', value: 'MM' },
  { label: '蒙古', code: 'MN', value: 'MN' },
  { label: '北马里亚纳', code: 'MP', value: 'MP' },
  { label: '马提尼克', code: 'MQ', value: 'MQ' },
  { label: '毛里塔尼亚', code: 'MR', value: 'MR' },
  { label: '蒙特塞拉特', code: 'MS', value: 'MS' },
  { label: '马耳他', code: 'MT', value: 'MT' },
  { label: '毛里求斯', code: 'MU', value: 'MU' },
  { label: '马尔代夫', code: 'MV', value: 'MV' },
  { label: '马拉维', code: 'MW', value: 'MW' },
  { label: '墨西哥', code: 'MX', value: 'MX' },
  { label: '马来西亚', code: 'MY', value: 'MY' },
  { label: '莫桑比克', code: 'MZ', value: 'MZ' },
  { label: '纳米尼亚', code: 'NA', value: 'NA' },
  { label: '新喀里多尼亚', code: 'NC', value: 'NC' },
  { label: '尼日尔', code: 'NE', value: 'NE' },
  { label: '诺福克岛', code: 'NF', value: 'NF' },
  { label: '尼日利亚', code: 'NG', value: 'NG' },
  { label: '尼加拉瓜', code: 'NI', value: 'NI' },
  { label: '荷兰', code: 'NL', value: 'NL' },
  { label: '挪威', code: 'NO', value: 'NO' },
  { label: '尼泊尔', code: 'NP', value: 'NP' },
  { label: '瑙鲁', code: 'NR', value: 'NR' },
  { label: '纽埃', code: 'NU', value: 'NU' },
  { label: '新西兰', code: 'NZ', value: 'NZ' },
  { label: '阿曼', code: 'OM', value: 'OM' },
  { label: '巴拿马', code: 'PA', value: 'PA' },
  { label: '秘鲁', code: 'PE', value: 'PE' },
  { label: '法属波利尼西亚', code: 'PF', value: 'PF' },
  { label: '巴布亚新几内亚', code: 'PG', value: 'PG' },
  { label: '菲律宾', code: 'PH', value: 'PH' },
  { label: '巴基斯坦', code: 'PK', value: 'PK' },
  { label: '波兰', code: 'PL', value: 'PL' },
  { label: '圣皮埃尔和密克隆', code: 'PM', value: 'PM' },
  { label: '皮特凯恩', code: 'PN', value: 'PN' },
  { label: '波多黎各', code: 'PR', value: 'PR' },
  { label: '巴勒斯坦', code: 'PS', value: 'PS' },
  { label: '葡萄牙', code: 'PT', value: 'PT' },
  { label: '帕劳', code: 'PW', value: 'PW' },
  { label: '巴拉圭', code: 'PY', value: 'PY' },
  { label: '卡塔尔', code: 'QA', value: 'QA' },
  { label: '留尼汪', code: 'RE', value: 'RE' },
  { label: '罗马尼亚', code: 'RO', value: 'RO' },
  { label: '俄罗斯', code: 'RU', value: 'RU' },
  { label: '卢旺达', code: 'RW', value: 'RW' },
  { label: '沙特阿拉伯', code: 'SA', value: 'SA' },
  { label: '所罗门群岛', code: 'SB', value: 'SB' },
  { label: '塞舌尔', code: 'SC', value: 'SC' },
  { label: '苏丹', code: 'SD', value: 'SD' },
  { label: '瑞典', code: 'SE', value: 'SE' },
  { label: '新加坡', code: 'SG', value: 'SG' },
  { label: '圣赫勒拿', code: 'SH', value: 'SH' },
  { label: '斯洛文尼亚', code: 'SI', value: 'SI' },
  { label: '斯瓦尔巴岛和扬马延岛', code: 'SJ', value: 'SJ' },
  { label: '斯洛伐克', code: 'SK', value: 'SK' },
  { label: '塞拉利昂', code: 'SL', value: 'SL' },
  { label: '圣马力诺', code: 'SM', value: 'SM' },
  { label: '塞内加尔', code: 'SN', value: 'SN' },
  { label: '索马里', code: 'SO', value: 'SO' },
  { label: '苏里南', code: 'SR', value: 'SR' },
  { label: '圣多美和普林西比', code: 'ST', value: 'ST' },
  { label: '萨尔瓦多', code: 'SV', value: 'SV' },
  { label: '叙利亚', code: 'SY', value: 'SY' },
  { label: '斯威士兰', code: 'SZ', value: 'SZ' },
  { label: '特克斯和凯科斯群岛', code: 'TC', value: 'TC' },
  { label: '乍得', code: 'TD', value: 'TD' },
  { label: '法属南部领土', code: 'TF', value: 'TF' },
  { label: '多哥', code: 'TG', value: 'TG' },
  { label: '泰国', code: 'TH', value: 'TH' },
  { label: '塔吉克斯坦', code: 'TJ', value: 'TJ' },
  { label: '托克劳', code: 'TK', value: 'TK' },
  { label: '土库曼斯坦', code: 'TM', value: 'TM' },
  { label: '突尼斯', code: 'TN', value: 'TN' },
  { label: '汤加', code: 'TO', value: 'TO' },
  { label: '东帝汶', code: 'TP', value: 'TP' },
  { label: '土耳其', code: 'TR', value: 'TR' },
  { label: '特立尼达和多巴哥', code: 'TT', value: 'TT' },
  { label: '图瓦卢', code: 'TV', value: 'TV' },
  { label: '坦桑尼亚', code: 'TZ', value: 'TZ' },
  { label: '乌克兰', code: 'UA', value: 'UA' },
  { label: '乌干达', code: 'UG', value: 'UG' },
  { label: '美国本土外小岛屿', code: 'UM', value: 'UM' },
  { label: '美国', code: 'US', value: 'US' },
  { label: '乌拉圭', code: 'UY', value: 'UY' },
  { label: '乌兹别克斯坦', code: 'UZ', value: 'UZ' },
  { label: '梵蒂冈', code: 'VA', value: 'VA' },
  { label: '圣文森特和格林纳丁斯', code: 'VC', value: 'VC' },
  { label: '委内瑞拉', code: 'VE', value: 'VE' },
  { label: '英属维尔京群岛', code: 'VG', value: 'VG' },
  { label: '美属维尔京群岛', code: 'VI', value: 'VI' },
  { label: '越南', code: 'VN', value: 'VN' },
  { label: '瓦努阿图', code: 'VU', value: 'VU' },
  { label: '瓦利斯和富图纳', code: 'WF', value: 'WF' },
  { label: '萨摩亚', code: 'WS', value: 'WS' },
  { label: '也门', code: 'YE', value: 'YE' },
  { label: '马约特', code: 'YT', value: 'YT' },
  { label: '南斯拉夫', code: 'YU', value: 'YU' },
  { label: '南非', code: 'ZA', value: 'ZA' },
  { label: '赞比亚', code: 'ZM', value: 'ZM' },
  { label: '津巴布韦', code: 'ZW', value: 'ZW' },
];

export const getRelationText = (code) => {
  const item = relation.filter((item) => item.code == code)[0];
  if (item) {
    return item.text;
  }
  return '';
};

export const getCertTypeText = (code) => {
  let type = certType.filter((item) => item.code == code)[0];
  return type ? type.text : '';
};

const genderMap = {
  M: '男',
  F: '女',
};
export const getGenderText = (code) => {
  return genderMap[code];
};

export const getYesNoText = (code, data = ['有', '无']) => {
  const index = code === 'Y' ? 0 : 1;
  return data[index];
};
