const menus = [
  {
    childs: [
      {
        id: 1194020,
        funName: 'MyMerits',
        funTitle: '我的绩效',
        funUrl: '/page1',
        funLogo: '',
        funMiniLogo: '',
        priority: 10,
        parentId: 1065001,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        childs: [
          {
            id: 1194016,
            funName: 'Dyejikaohe',
            funTitle: '业绩考核',
            funUrl: 'https://hrm.zuifuli.com/#/merits/LeaderPerformManage/0',
            funLogo: '',
            funMiniLogo: '',
            priority: -1,
            parentId: 1195008,
            expireDate: '2999-12-31 23:59:59',
            effectiveDate: '1970-01-01 01:01:01',
            ext: '',
            tag: '',
            cfgUrl: '',
            detailUrl: '',
            tripartiteIndenture: 'N',
          },
          {
            id: 1194017,
            funName: 'Dwenhuakaohe',
            funTitle: '文化考核',
            funUrl: 'https://hrm.zuifuli.com/#/merits/LeaderPerformManage/1',
            funLogo: '',
            funMiniLogo: '',
            priority: 10,
            parentId: 1195008,
            expireDate: '2999-12-31 23:59:59',
            effectiveDate: '1970-01-01 01:01:01',
            ext: '',
            tag: '',
            cfgUrl: '',
            detailUrl: '',
            tripartiteIndenture: 'N',
          },
          {
            id: 1195009,
            funName: 'Dqitakaohe',
            funTitle: '其他考核',
            funUrl: 'https://hrm.zuifuli.com/#/merits/LeaderOtherPerformManage',
            funLogo: '',
            funMiniLogo: '',
            priority: 20,
            parentId: 1195008,
            expireDate: '2999-12-31 23:59:59',
            effectiveDate: '1970-01-01 01:01:01',
            ext: '',
            tag: '',
            cfgUrl: '',
            detailUrl: '',
            tripartiteIndenture: 'N',
          },
        ],
        id: 1195008,
        funName: 'bumenjixiao',
        funTitle: '部门绩效管理',
        funUrl: '',
        funLogo: '',
        funMiniLogo: '',
        priority: 11,
        parentId: 1065001,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        childs: [
          {
            id: 1078003,
            funName: 'InventoryManagement',
            funTitle: '盘点管理',
            funUrl: 'https://one.zuifuli.com/hr/genius/list',
            funLogo: '',
            funMiniLogo: '',
            priority: -1,
            parentId: 1078001,
            expireDate: '2999-12-31 23:59:59',
            effectiveDate: '1970-01-01 01:01:01',
            ext: '',
            tag: '',
            cfgUrl: '',
            detailUrl: '',
            tripartiteIndenture: 'N',
          },
          {
            id: 1078002,
            funName: 'TeamInventory',
            funTitle: '团队盘点',
            funUrl: 'https://one.zuifuli.com/hr/genius/leader',
            funLogo: '',
            funMiniLogo: '',
            priority: 1,
            parentId: 1078001,
            expireDate: '2999-12-31 23:59:59',
            effectiveDate: '1970-01-01 01:01:01',
            ext: '',
            tag: '',
            cfgUrl: '',
            detailUrl: '',
            tripartiteIndenture: 'N',
          },
        ],
        id: 1078001,
        funName: 'Talentinventory',
        funTitle: '人才盘点',
        funUrl: '',
        funLogo: '',
        funMiniLogo: '',
        priority: 90,
        parentId: 1065001,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        childs: [
          {
            id: 1087001,
            funName: 'NominationManager',
            funTitle: '提名确认',
            funUrl: 'https://one.zuifuli.com/hr/promotion/hr',
            funLogo: '',
            funMiniLogo: '',
            priority: 103,
            parentId: 1086001,
            expireDate: '2999-12-31 23:59:59',
            effectiveDate: '1970-01-01 01:01:01',
            ext: '',
            tag: '',
            cfgUrl: '',
            detailUrl: '',
            defaultEnable: 'N',
            tripartiteIndenture: 'N',
          },
          {
            id: 1086002,
            funName: 'PromotionManager',
            funTitle: '晋升提名',
            funUrl: 'https://one.zuifuli.com/hr/promotion/leader',
            funLogo: '',
            funMiniLogo: '',
            priority: 104,
            parentId: 1086001,
            expireDate: '2999-12-31 23:59:59',
            effectiveDate: '1970-01-01 01:01:01',
            ext: '',
            tag: '',
            cfgUrl: '',
            detailUrl: '',
            defaultEnable: 'N',
            tripartiteIndenture: 'N',
          },
        ],
        id: 1086001,
        funName: 'PromotionNomination',
        funTitle: '晋升提名',
        funUrl: '',
        funLogo: '',
        funMiniLogo: '',
        priority: 100,
        parentId: 1065001,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        funType: 'N',
        cfgUrl: '',
        detailUrl: '',
        defaultEnable: 'N',
        tripartiteIndenture: 'N',
      },
    ],
    id: 1065001,
    funName: 'hrManage',
    funTitle: '人事管理',
    funUrl: '',
    funLogo: 'magi-hr',
    funMiniLogo: '',
    priority: -999,
    parentId: 1022001,
    expireDate: '2999-12-31 23:59:59',
    effectiveDate: '1970-01-01 01:01:01',
    ext: '',
    tag: '',
    cfgUrl: '',
    detailUrl: '',
    tripartiteIndenture: 'N',
  },
  {
    childs: [
      {
        childs: [
          {
            id: 1114001,
            funName: 'myOAnew',
            funTitle: '我的OA',
            funUrl:
              'https://oaplus.zuifuli.com/home?#/office/pc/task/myoaplus?hideCategorys=2160001',
            funLogo: '',
            funMiniLogo: '',
            priority: -1,
            parentId: 1111002,
            expireDate: '2999-12-31 23:59:59',
            effectiveDate: '1970-01-01 01:01:01',
            ext: '',
            tag: '',
            cfgUrl: '',
            detailUrl: '',
            tripartiteIndenture: 'N',
          },
        ],
        id: 1111002,
        funName: 'OAoffice',
        funTitle: 'OA办公',
        funUrl: '',
        funLogo: '',
        funMiniLogo: '',
        priority: -2,
        parentId: 1066002,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '1',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        id: 1182002,
        funName: 'documentcenter',
        funTitle: '文档中心',
        funUrl: 'https://oaplus.zuifuli.com/home#/third/pc/folder/center?biztype=center&id=-1',
        funLogo: '',
        funMiniLogo: '',
        priority: -1,
        parentId: 1066002,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        childs: [
          {
            id: 1182001,
            funName: 'myWorkSystem',
            funTitle: '我的工单',
            funUrl:
              'https://one.zuifuli.com/outside?funUrl=https%3A%2F%2Foaplus1.zuifuli.com%2Fhome%2F%23%2Foffice%2Fpc%2Ftask%2Fmyoaplus?showCategorys=2160001',
            funLogo: '',
            funMiniLogo: '',
            priority: -1,
            parentId: 1181001,
            expireDate: '2999-12-31 23:59:59',
            effectiveDate: '1970-01-01 01:01:01',
            ext: '',
            tag: '',
            cfgUrl: '',
            detailUrl: '',
            tripartiteIndenture: 'N',
          },
        ],
        id: 1181001,
        funName: 'workSystem',
        funTitle: '工单管理',
        funUrl: '',
        funLogo: '',
        funMiniLogo: '',
        priority: -1,
        parentId: 1066002,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        id: 1091001,
        funName: 'kehuguanli',
        funTitle: 'CRM客户管理',
        funUrl: 'https://one.zuifuli.com/entrances/crm',
        funLogo: '',
        funMiniLogo: '',
        priority: 10,
        parentId: 1066002,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        id: 1189001,
        funName: 'calendar',
        funTitle: '日程管理',
        funUrl:
          'https://one.zuifuli.com/outside?redirectUrl=https%3A%2F%2Fwww.zuifuli.com%2Fweb%2Fcalendar%2F',
        funLogo: '',
        funMiniLogo: '',
        priority: 98,
        parentId: 1066002,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        defaultEnable: 'N',
        tripartiteIndenture: 'N',
      },
    ],
    id: 1066002,
    funName: 'nOA',
    funTitle: '协同办公',
    funUrl: '',
    funLogo: 'magi-oa',
    funMiniLogo: '',
    priority: -997,
    parentId: 1022001,
    expireDate: '2999-12-31 23:59:59',
    effectiveDate: '1970-01-01 01:01:01',
    ext: '',
    tag: '',
    cfgUrl: '',
    detailUrl: '',
    tripartiteIndenture: 'N',
  },
  {
    childs: [
      {
        id: 1178001,
        funName: 'videoConference',
        funTitle: '视频会议',
        funUrl: 'https://magic.zuifuli.com/admin/videoConference/videoConferenceList',
        funLogo: '',
        funMiniLogo: '',
        priority: -1,
        parentId: 1177002,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
    ],
    id: 1177002,
    funName: 'videomeetings',
    funTitle: '视频会议',
    funUrl: '',
    funLogo: '',
    funMiniLogo: '',
    priority: -1,
    parentId: 1022001,
    expireDate: '2999-12-31 23:59:59',
    effectiveDate: '1970-01-01 01:01:01',
    ext: '',
    tag: '',
    cfgUrl: '',
    detailUrl: '',
    tripartiteIndenture: 'N',
  },
  {
    childs: [
      {
        id: 1104001,
        funName: 'MyProject',
        funTitle: '我的项目',
        funUrl: 'https://one.zuifuli.com/outside?funUrl=https://pm.zuifuli.com/pm/operation/list',
        funLogo: '',
        funMiniLogo: '',
        priority: 1,
        parentId: 1103001,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        funType: 'N',
        cfgUrl: '',
        detailUrl: '',
        defaultEnable: 'N',
        tripartiteIndenture: 'N',
      },
      {
        id: 1103002,
        funName: 'ProjectAlication',
        funTitle: '我的申请',
        funUrl: 'https://one.zuifuli.com/outside?funUrl=https://pm.zuifuli.com/pm/operation/apply',
        funLogo: '',
        funMiniLogo: '',
        priority: 2,
        parentId: 1103001,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        id: 1103003,
        funName: 'ProjectApproval',
        funTitle: '我的审批',
        funUrl:
          'https://one.zuifuli.com/outside?funUrl=https://pm.zuifuli.com/pm/operation/approval',
        funLogo: '',
        funMiniLogo: '',
        priority: 3,
        parentId: 1103001,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
    ],
    id: 1103001,
    funName: 'ProjectManagement',
    funTitle: '项目管理',
    funUrl: '',
    funLogo: '',
    funMiniLogo: '',
    priority: -1,
    parentId: 1022001,
    expireDate: '2999-12-31 23:59:59',
    effectiveDate: '1970-01-01 01:01:01',
    ext: '',
    tag: '',
    funType: 'N',
    cfgUrl: '',
    detailUrl: '',
    defaultEnable: 'N',
    tripartiteIndenture: 'N',
  },
  {
    childs: [
      {
        id: 1036010,
        funName: 'examineApprove',
        funTitle: '合同审批',
        funUrl: 'https://one.zuifuli.com/hr/contract/examineApprove',
        funLogo: '',
        funMiniLogo: '',
        priority: 1,
        parentId: 1037014,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        id: 1037015,
        funName: 'partner',
        funTitle: '签约方管理',
        funUrl: 'https://one.zuifuli.com/hr/contract/partner',
        funLogo: '',
        funMiniLogo: '',
        priority: 2,
        parentId: 1037014,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
      {
        id: 1053010,
        funName: 'relatedParty',
        funTitle: '关联方管理',
        funUrl: 'https://one.zuifuli.com/hr/contract/related',
        funLogo: '',
        funMiniLogo: '',
        priority: 3,
        parentId: 1037014,
        expireDate: '2999-12-31 23:59:59',
        effectiveDate: '1970-01-01 01:01:01',
        ext: '',
        tag: '10',
        cfgUrl: '',
        detailUrl: '',
        tripartiteIndenture: 'N',
      },
    ],
    id: 1037014,
    funName: 'contractmanagement',
    funTitle: '合同管理-科技',
    funUrl: '',
    funLogo: '',
    funMiniLogo: '',
    priority: -1,
    parentId: 1022001,
    expireDate: '2999-12-31 23:59:59',
    effectiveDate: '1970-01-01 01:01:01',
    ext: '',
    tag: '',
    cfgUrl: '',
    detailUrl: '',
    tripartiteIndenture: 'N',
  },
];

export default menus;
